# Generated by Django 2.1.5 on 2019-01-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
                ('programming_language', models.CharField(max_length=255)),
                ('default_version', models.CharField(max_length=255)),
                ('default_branch', models.CharField(max_length=255)),
                ('repo_type', models.CharField(max_length=255)),
                ('repo', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('language', models.CharField(max_length=255)),
                ('documentation_type', models.CharField(max_length=255)),
                ('canonical_url', models.CharField(max_length=255)),
                ('actual_language', models.CharField(max_length=255, verbose_name='detected language')),
            ],
        ),
    ]
