# Generated by Django 2.1.5 on 2019-01-19 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readthedocs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='actual_language',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='detected language'),
        ),
    ]
