# Generated by Django 2.1.5 on 2019-01-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readthedocs', '0002_auto_20190119_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='license',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
